#! /usr/bin/env python3
import os
import argparse
import PyPDF4


def parse_args():
    parser = argparse.ArgumentParser(prog='encpdf', description='utility encrypting pdf file.')
    parser.add_argument('-f', '--pdffile', type=str, required=True, help='pdf file name.')
    parser.add_argument('-p', '--password',  type=str, required=True, help='password encrypting.')
    args = parser.parse_args()
    return args.pdffile, args.password


def encpdf(pdffile, passwd, file_out):
    pdf = PyPDF4.PdfFileReader(pdffile)
    pdf_out = PyPDF4.PdfFileWriter()
    pdf_out.appendPagesFromReader(pdf)
    pdf_out.encrypt(passwd)
    pdf_out.write(open(file_out, 'wb'))
    return 0


def main():
    pdffile, passwd = parse_args()
    file_out = os.path.join(os.path.dirname(pdffile), '.'.join(os.path.basename(pdffile).split('.')[:-1]) + '_enc.pdf')

    encpdf(pdffile, passwd, file_out)
    return 0


if __name__ == "__main__":
    main()
